import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:share_plus/share_plus.dart';

abstract interface class DocxShareService {
  Future<void> shareDocx({
    required String filePath,
  });
}

final docxShareServiceProvider = Provider<DocxShareService>((ref) {
  return const SharePlusDocxShareService();
});

final class SharePlusDocxShareService implements DocxShareService {
  const SharePlusDocxShareService();

  @override
  Future<void> shareDocx({
    required String filePath,
  }) async {
    await Share.shareXFiles(
      [
        XFile(
          filePath,
          mimeType:
              'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ),
      ],
      subject: 'Resume',
      text: 'Generated by Resume Labs',
    );
  }
}
