// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0i7mp8ZOZJzNtIsqqmLZd3uWXpAMpO0E',
    appId: '1:346453081708:web:be8b6defaaefa65eab2249',
    messagingSenderId: '346453081708',
    projectId: 'resume-labs-cdc63',
    authDomain: 'resume-labs-cdc63.firebaseapp.com',
    storageBucket: 'resume-labs-cdc63.firebasestorage.app',
    measurementId: 'G-BK0Z5E7T1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlqVxlLAiIUZVKOpBwQ1WhpIJsHoT2kaI',
    appId: '1:346453081708:android:ad540f3de23a88bdab2249',
    messagingSenderId: '346453081708',
    projectId: 'resume-labs-cdc63',
    storageBucket: 'resume-labs-cdc63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEOdfwJMmJnCNKhcmkPHc9cb1oFLKCnHM',
    appId: '1:346453081708:ios:9c01d5df7d266395ab2249',
    messagingSenderId: '346453081708',
    projectId: 'resume-labs-cdc63',
    storageBucket: 'resume-labs-cdc63.firebasestorage.app',
    iosClientId: '346453081708-42sjllvvup56b3roq5eka0gn4dd62ra8.apps.googleusercontent.com',
    iosBundleId: 'com.nextfiction.resumelabs.ai.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEOdfwJMmJnCNKhcmkPHc9cb1oFLKCnHM',
    appId: '1:346453081708:ios:22351e1c2b319063ab2249',
    messagingSenderId: '346453081708',
    projectId: 'resume-labs-cdc63',
    storageBucket: 'resume-labs-cdc63.firebasestorage.app',
    iosClientId: '346453081708-qklpc6tp71mjq2ii1oo4cbqkgbjsrj2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumeLabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0i7mp8ZOZJzNtIsqqmLZd3uWXpAMpO0E',
    appId: '1:346453081708:web:238c1edc8f5abf9bab2249',
    messagingSenderId: '346453081708',
    projectId: 'resume-labs-cdc63',
    authDomain: 'resume-labs-cdc63.firebaseapp.com',
    storageBucket: 'resume-labs-cdc63.firebasestorage.app',
    measurementId: 'G-65ZLSFGBJZ',
  );

}