// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0i7mp8ZOZJzNtIsqqmLZd3uWXpAMpO0E',
    appId: '1:346453081708:web:ed3704fba76ea732ab2249',
    messagingSenderId: '346453081708',
    projectId: 'resume-labs-cdc63',
    authDomain: 'resume-labs-cdc63.firebaseapp.com',
    storageBucket: 'resume-labs-cdc63.firebasestorage.app',
    measurementId: 'G-EMGMVWRCXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlqVxlLAiIUZVKOpBwQ1WhpIJsHoT2kaI',
    appId: '1:346453081708:android:a55236899fab877dab2249',
    messagingSenderId: '346453081708',
    projectId: 'resume-labs-cdc63',
    storageBucket: 'resume-labs-cdc63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEOdfwJMmJnCNKhcmkPHc9cb1oFLKCnHM',
    appId: '1:346453081708:ios:efdee746ef6e6cd6ab2249',
    messagingSenderId: '346453081708',
    projectId: 'resume-labs-cdc63',
    storageBucket: 'resume-labs-cdc63.firebasestorage.app',
    iosBundleId: 'com.nextfiction.resumeLabs',
  );
}
